"""
Smallstep CA UI configuration.

The PostgreSQL password and the revocation JWK are both generated by
init-ca.sh and mounted read-only from secrets files — nothing secret is
hardcoded here, so this file is safe to commit. Everything else is a plain
constant — edit as needed.
"""

import json
import secrets
import time
from pathlib import Path

import psycopg2


def _read_pg_password() -> str:
    # Mounted read-only into the container; falls back to a placeholder if absent.
    for p in ("/run/secrets/pg_password", "/app/secrets/pg_password.txt"):
        f = Path(p)
        if f.is_file():
            return f.read_text().strip()
    return "CHANGEME"


def _read_revoke_jwk() -> tuple:
    # Written by init-ca.sh (decrypted JWK provisioner key), mounted read-only.
    # Absent until init-ca.sh has run, in which case revocation stays disabled.
    f = Path("/app/secrets/revoke_jwk.json")
    if f.is_file():
        try:
            data = json.loads(f.read_text())
            return data.get("kid", ""), data.get("jwk")
        except (ValueError, OSError):
            pass
    return "", None


# --- PostgreSQL (step-ca database) ------------------------------------------
DB_DSN = f"postgresql://stepca:{_read_pg_password()}@pki-db:5432/stepca?sslmode=disable"


# Arbitrary constant, shared with app.py's own migration: serializes schema
# setup across the 4 uvicorn worker processes that import these modules
# concurrently. Without it, two workers racing on the same
# `CREATE TABLE IF NOT EXISTS` can both decide the table is missing and hit
# psycopg2.errors.UniqueViolation on the catalog insert.
MIGRATION_LOCK_KEY = 951413027


def connect_with_retry(attempts: int = 10, delay: float = 1.5):
    """
    Connect to Postgres, retrying briefly. Used only for startup migrations:
    the postgres image's own startup (initdb -> temporary instance -> restart)
    has a short window where pg_isready can pass just before the real server
    is accepting connections, and this code runs before request-time error
    handling exists.
    """
    last_err = None
    for _ in range(attempts):
        try:
            return psycopg2.connect(DB_DSN)
        except psycopg2.OperationalError as e:
            last_err = e
            time.sleep(delay)
    raise last_err


def _get_or_create_secret_key() -> str:
    # uvicorn runs 4 worker processes, each importing this module independently,
    # so the Flask session-signing key can't just be a random value picked at
    # import time (workers would sign with different keys and invalidate each
    # other's sessions). Persist it in the stepca database instead, so every
    # worker (and every restart) converges on the same value.
    with connect_with_retry() as conn, conn.cursor() as cur:
        cur.execute("SELECT pg_advisory_lock(%s)", (MIGRATION_LOCK_KEY,))
        try:
            cur.execute(
                "CREATE TABLE IF NOT EXISTS dashboard_settings ("
                "  key   text PRIMARY KEY,"
                "  value text NOT NULL)"
            )
            cur.execute(
                "INSERT INTO dashboard_settings (key, value) VALUES ('flask_secret_key', %s) "
                "ON CONFLICT (key) DO NOTHING",
                (secrets.token_hex(32),),
            )
            cur.execute("SELECT value FROM dashboard_settings WHERE key = 'flask_secret_key'")
            result = cur.fetchone()[0]
            # Commit BEFORE releasing the lock: otherwise the next waiter's own
            # CREATE TABLE IF NOT EXISTS runs while this one is still
            # uncommitted, sees no table yet, and races it at the catalog
            # level (psycopg2.errors.UniqueViolation on pg_type).
            conn.commit()
            return result
        finally:
            # No-op if already committed above; rolls back an aborted
            # transaction if the try block raised, so the unlock statement
            # below isn't itself rejected with InFailedSqlTransaction.
            conn.rollback()
            cur.execute("SELECT pg_advisory_unlock(%s)", (MIGRATION_LOCK_KEY,))
            conn.commit()


# --- Dashboard login ----------------------------------------------------------
SECRET_KEY = _get_or_create_secret_key()

# --- Revocation -------------------------------------------------------------
# Enabled automatically once init-ca.sh has written volumes/stepca/secrets/
# revoke_jwk.json. Revocation uses step-ca's HTTP API — no subprocess, no
# docker socket.
CA_URL = "https://pki:443"            # docker-network address actually contacted
# step-ca authorizes provisioner tokens by matching the JWT "aud" claim against
# its own configured dnsNames (see ca.json) — that's pki.example.com, not the
# "pki" service name above, so the token audience must be built from this one.
CA_AUDIENCE = "https://pki.example.com:443"
CA_VERIFY = False                    # or "/app/root_ca.crt" for strict verification
REVOKE_PROVISIONER_NAME = "jwk"
REVOKE_PROVISIONER_KID, REVOKE_PROVISIONER_JWK = _read_revoke_jwk()
REVOKE_ENABLED = REVOKE_PROVISIONER_JWK is not None

# --- Server -----------------------------------------------------------------
# Only used by `python app.py` for local dev; the container runs uvicorn/asgi.py.
LISTEN_HOST = "0.0.0.0"
LISTEN_PORT = 5000
